In [64]:
import pandas as pd
import googlemaps
from datetime import datetime
import json
import requests
import math
import numpy as np

# suburbs is a pandas dataframe read from a csv file. suburbs has only one column called suburb and lists Brisbane
# suburbs.
suburbs = pd.read_csv("suburbs.csv")

# API key removed for security reasons
API_KEY = 'AIzaSyDno02LrvxPEu1BoS8GmJyN5Avb5Fof58M'

In [4]:
# TESTING PURPOSES: 
# A small Series called common_suburbs with a subset of common suburbs is created so API calls are minimised in 
# testing. For every element of common_suburbs, spaces are replaced with + and ,QLD is appended to the end. Then, 
# the elements are concatenated into a string with a | separator and assigned to common_suburbs_str.
common_suburbs = suburbs['common_suburb'][:7]
common_suburbs = common_suburbs.str.replace(" ", "+") + ',QLD'
common_suburbs_str = common_suburbs.str.cat(sep="|")

response = requests.get(f'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins={common_suburbs_str}&destinations={common_suburbs_str}&mode=transit&key={API_KEY}')

In [53]:
# Take duration_str as a string in the format of:
# Y min(s) or X hour(s) Y min(s) where '(s)' represents the optional plurality of the noun
# and return an integer representing total mins in duration.
def duration_str_to_mins(duration_str):
    duration_lst = duration_str.split(' ')
    mins = int(duration_lst[-2])
    if (len(duration_lst) == 4):
        hours = int(duration_lst[0])
        mins += hours * 60
    return mins

In [57]:
# Parses the response string from Google Distance Matrix API and stores the journey durations into a dataframe indexed
# by suburb names called journey_df. All durations are converted into a numeric type representing minutes. DataFrame
# row indexes represent suburb travelling from and column indexes represent suburb travelling to.

dict_response = json.loads(response.text)
journeys_list_2d = []

for routes_from_suburb in dict_response['rows']:
    duration_list = []
    for route in routes_from_suburb['elements']:
        duration = duration_str_to_mins(route['duration']['text'])
        # duration of 1 min represents a suburb to itself, so logically set it to 0
        if (duration == 1):
            duration = 0
        duration_list.append(duration)
    journeys_list_2d.append(duration_list)

common_suburbs_lst = suburbs['common_suburb'][:7].tolist()
journey_df = pd.DataFrame(journeys_list_2d, index=common_suburbs_lst, columns=common_suburbs_lst)
journey_df

,Brisbane Airport,Brisbane City,Algester,Archerfield,Ascot,Ashgrove,Auchenflower
Brisbane Airport,0,46,98,96,60,73,67
Brisbane City,48,0,47,52,27,18,19
Algester,89,45,0,42,84,73,67
Archerfield,97,60,56,0,86,75,69
Ascot,44,28,77,76,0,49,43
Ashgrove,67,21,78,63,55,0,35
Auchenflower,61,22,70,70,57,31,0